#web:
#  build: ./web
#  command: python -u ./web/app.py
#  ports:
#    - "5000:5000"
#  volumes:
#    - .:/app
#  links:
#    - db
#  environment:
#   - POSTGRES_PASSWORD=mysecretpassword

trawler:
  build: .
  command: python -u ./trawler.py
  volumes:
    - .:/app
  links:
    - db
  environment:
   - POSTGRES_PASSWORD=mysecretpassword
   
db:
  image: postgres
  environment:
      - POSTGRES_PASSWORD=mysecretpassword
